### ISSUE TITLE
TypeError: Cannot read property '1' of null : addMissingGame

### ISSUE THREAD

**Issue by Kekwel** [RudeySH/achievement-tracker-comparer#1]
Hi !

I just updated the script and when I try to find differences between the new trackers, I've got this error :
![image](https://user-images.githubusercontent.com/9060357/122977829-21c44c80-d396-11eb-989e-4a8b3ac47b72.png)

If I try with only Astats and SH, it works fine, but not when I check one of the others.
And the error point to this line :
`name: document.body.innerHTML.match(/'SetContentTitle', '(.*) Achievements'/)[1],`

I don't know if I need to give you more informations, but you can ask !

**Comment by RudeySH** [comment]
This can happen when the Steam website isn't displayed in English. I just fixed this in version 1.0.8. Can you try again and confirm or deny that this error is no longer occurring?

**Comment by Kekwel** [comment]
Yes indeed ! Thanks !
