### ISSUE TITLE
Error on Profile sub pages

### ISSUE THREAD

**Issue by TrentexTech** [RudeySH/achievement-tracker-comparer#3]
The extension isn't able to retrieve Profile data on Profile sub pages like 
https://steamcommunity.com/id/TrentexTech/badges/
and giving the following error code
```
Script error in [Greasemonkey script https://github.com/RudeySH/achievement-tracker-comparer/Achievement Tracker Comparer; version 1.0.12]:
TypeError: profileData is undefined              Achievement Tracker Comparer:1085:19
    <anonymous> user-script:https://github.com/RudeySH/achievement-tracker-comparer/Achievement Tracker Comparer:1085
```
the Extension should only check for Profile data on the man profile page.

**Comment by RudeySH** [comment]
Hi, thanks for bringing this to my attention. This is now fixed in v1.0.13.
